name: Update Images

on:
  push:
    paths:
      - 'pictures/**'
      - 'images.js'  # Trigger on changes to images.js as well
  workflow_dispatch:

jobs:
  update-images-js:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master  # Adjust to your default branch

      - name: Change directory to repository root
        run: cd $GITHUB_WORKSPACE

      - name: Debug Directory Contents
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Pictures directory contents:"
          ls -la pictures/

      - name: Run updateMosaic.js
        run: |
          node updateMosaic.js
          echo "Generated images.js contents:"
          cat images.js

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add images.js
          git commit -m "Update images.js [skip ci]" || echo "No changes to commit"
          git push
