name: Update Image Gallery

on:
  push:
    paths:
      - 'gallery/pictures/**'  # Triggers on changes to the pictures directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Image List
        run: |
          echo "const images = [" > images.js
          for f in gallery/pictures/*; do
            echo "  '$(basename "$f")'," >> images.js
          done
          echo "];" >> images.js

      - name: Update index.html
        run: |
          echo "<!DOCTYPE html>
          <html lang='en'>
          <head>
              <meta charset='UTF-8'>
              <meta name='viewport' content='width=device-width, initial-scale=1.0'>
              <title>Image Gallery</title>
              <link rel='stylesheet' href='styles.css'>
              <style>
                  body { font-family: Arial, sans-serif; display: flex; flex-direction: column; align-items: center; background-color: #f4f4f4; }
                  h1 { margin: 20px; }
                  #gallery { display: flex; flex-wrap: wrap; justify-content: center; }
                  #gallery img { margin: 10px; width: 200px; height: auto; border: 2px solid #ccc; border-radius: 4px; transition: transform 0.2s; }
                  #gallery img:hover { transform: scale(1.05); }
              </style>
          </head>
          <body>
              <h1>My Image Gallery</h1>
              <div id='gallery'></div>
              <script src='images.js'></script>
              <script>
                  const gallery = document.getElementById('gallery');
                  images.forEach(image => {
                      const imgElement = document.createElement('img');
                      imgElement.src = 'pictures/' + image;
                      imgElement.alt = image;
                      gallery.appendChild(imgElement);
                  });
              </script>
          </body>
          </html>" > gallery/index.html
        working-directory: gallery
