name: Update Images

on:
  push:
    paths:
      - 'gallery/pictures/**'  # Trigger when there are changes in the pictures folder

jobs:
  update-images-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify your desired Node version

      - name: Install Dependencies
        run: npm install

      - name: Run updateMosaic.js
        run: node gallery/updateMosaic.js # Ensure the correct path to your script

      - name: Commit images.js
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gallery/images.js   # Ensure this path is correct
          git commit -m "Update images.js automatically" || echo "No changes to commit"
          git push
