name: 917

on:
  push:
    paths:
      - 'majortom/917/pictures/**'
      - 'majortom/917.html'
  workflow_dispatch:

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate 917.html
        run: |
          echo "Generating 917.html..."
          cat <<EOL > majortom/917.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Brunurb</title>
            <link rel="stylesheet" href="main.css">
          </head>
          <style>
          #myMosaic { margin: 0; padding: 0; display: flex; flex-wrap: wrap; justify-content: center; margin-top: 20px; }
          #myMosaic img { border: none; max-width: calc(100% / 8); height: auto; cursor: pointer; }
          h1 { text-align: center; color: #dedcff; margin: 80px 0 14px; font-size: 14px; }
          #overlay { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.8); display: none; z-index: 1000; justify-content: center; align-items: center; }
          #overlay.show { display: flex; }
          .overlay-content { display: flex; justify-content: center; align-items: center; max-width: 90%; max-height: 90%; }
          #overlay img { max-width: 100%; max-height: 100%; display: block; }
          #close { position: absolute; top: 20px; right: 30px; font-size: 40px; color: white; cursor: pointer; }
          </style>
          <body>

            <header>
              <ul class="navbar-top">
                <li id="nav-company">
                  <a href="https://brunurb.github.io">brunurb</a>
                </li>
                <li><a href="https://brunurb.github.io/">Home</a></li>
                <li class="dropdown">
                  <a href="#">About ▼</a>
                  <ul class="dropdown-menu">
                    <li><a href="https://brunurb.github.io/mooo/index.html">About</a></li>
                    <li><a href="https://brunurb.github.io/web">links</a></li>
                    <li><a href="mailto:eargdu3d5@mozmail.com">Contact</a></li>
                  </ul>
                </li>
                <li><a href="https://brunurb.github.io/majortom/">Portfolio</a></li>
                <li><a href="https://old.reddit.com/r/brunurb/" target="_blank">Blog</a></li>
                <li class="dropdown">
                  <a href="#">Works ▼</a>
                  <ul class="dropdown-menu">
                    <li><a href="https://brunurb.github.io/mooo">Presentations</a></li>
                    <li><a href="https://brunurb.github.io/majortom/prettymaps">prettymaps</a></li>
                    <li><a href="https://brunurb.github.io/majortom/sketchup">sketchup</a></li>
                    <li><a href="https://brunurb.github.io/majortom/vectors">vectors</a></li>
                    <li><a href="https://brunurb.github.io/web">Website 2</a></li>
                    <li><a href="https://brunurb.github.io/majortom">8bit</a></li>
                    <li><a href="https://brunurb.github.io/shortcuts">Shortcuts</a></li>
                    <li><a href="https://brunurb.github.io/startpage">Startpage</a></li>
                  </ul>
                </li>
              </ul>
            </header>
          <main>
          <h1>Porsche 917</h1>
          <div id="myMosaic">
          EOL
          for img in $(ls majortom/917/pictures | grep -E '\.jpeg$|\.jpg$|\.gif$|\.svg$|\.png$|\.webp$'); do
            echo "<img src='https://brunurb.github.io/majortom/917/pictures/$img' alt='Gallery Image' data-full='https://brunurb.github.io/majortom/917/pictures/$img' class='thumbnail' onclick='showImage(this.dataset.full)' />" >> majortom/917.html
          done
          cat <<EOL >> majortom/917.html
          </div>
          <div id="overlay" onclick="closeOverlay(event)">
            <div class="overlay-content">
              <span id="close">×</span>
              <img id="overlay-image" src="" alt="Full Size Image" />
            </div>
          </div>
          </main>
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
          <script type="text/javascript">
          document.addEventListener("DOMContentLoaded", function() {
              function showImage(src) {
                  const overlay = document.getElementById("overlay");
                  const overlayImage = document.getElementById("overlay-image");
                  overlayImage.src = src;
                  overlay.classList.add("show");
              }
              function closeOverlay(event) {
                  if (event.target.id === "overlay" || event.target.id === "close") {
                      const overlay = document.getElementById("overlay");
                      overlay.classList.remove("show");
                  }
              }
              const images = document.querySelectorAll("#myMosaic img");
              images.forEach(image => {
                  image.addEventListener("click", function() {
                      showImage(this.dataset.full);
                  });
              });
              const overlay = document.getElementById("overlay");
              overlay.addEventListener("click", closeOverlay);
              const closeButton = document.getElementById("close");
              closeButton.addEventListener("click", closeOverlay);
          });
          </script>
            <footer>
              <p>&copy; 2024 brunurb</p>
            </footer>
          </body>
          </html>
          EOL

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Action"
          git add majortom/917.html
          git commit -m "Regenerate majortom/917.html for mosaic gallery with overlay" || echo "No changes to commit"
          git push origin master  # Make sure this matches your main branch
