name: 917

on:
  push:
    paths:
      - 'majortom/917/pictures/**'
      - 'majortom/917.html'
  workflow_dispatch:

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate 917.html
        run: |
          echo "Generating 917.html..."
          echo '<!DOCTYPE html><html lang="en">' > majortom/917.html
          echo '<head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0">' >> majortom/917.html
          echo '<title>Porsche 917</title>' >> majortom/917.html
          echo '<link rel="preconnect" href="https://fonts.googleapis.com">' >> majortom/917.html
          echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>' >> majortom/917.html
          echo '<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">' >> majortom/917.html
          echo '<link rel="stylesheet" href="https://unpkg.com/nes.css/css/nes.css" />' >> majortom/917.html
          echo '<link rel="stylesheet" type="text/css" href="majortom/jquery.mosaic.css" />' >> majortom/917.html  # Include the mosaic CSS
          echo '<style>' >> majortom/917.html
          echo 'body { background-color: #142936; color: #92cfbf; margin: 0; font-family: "Press Start 2P", cursive; }' >> majortom/917.html
          echo '.header { position: fixed; top: 0; left: 0; right: 0; background-color: #224357; padding: 5px; display: flex; justify-content: space-between; align-items: center; box-shadow: 0px 4px 10px rgba(8, 17, 23, 0.9); z-index: 10; }' >> majortom/917.html
          echo '.header a { color: #cd3162; text-decoration: none; font-family: "Press Start 2P", cursive; font-size: 1em; }' >> majortom/917.html
          echo '.buttons { display: flex; gap: 2px; }' >> majortom/917.html
          echo '.nes-btn { margin-right: 2px; }' >> majortom/917.html
          echo '.nes-btn:last-child { margin-right: 0; }' >> majortom/917.html
          echo '#myMosaic { margin: 0; padding: 0; display: flex; flex-wrap: wrap; justify-content: center; max-width: 100%; }' >> majortom/917.html
          echo 'img { margin: 5px; display: block; border: none; height: auto; }' >> majortom/917.html
          echo 'footer { text-align: left; padding: 10px; font-size: 10px; background-color: #224357; color: #92cfbf; }' >> majortom/917.html
          echo 'footer a { color: inherit; text-decoration: none; }' >> majortom/917.html
          echo '</style></head><body>' >> majortom/917.html

          # Header
          echo '<div class="header">' >> majortom/917.html
          echo '  <a href="https://brunurb.github.io/"><span class="nes-icon home is-small"></span> brunurb</a>' >> majortom/917.html
          echo '  <div class="buttons">' >> majortom/917.html
          echo '  <a href="https://brunurb.github.io/astronaut"><button type="button" class="nes-btn is-primary">Astronaut</button></a>' >> majortom/917.html
          echo '  <a href="https://brunurb.github.io/spacecraft"><button type="button" class="nes-btn is-success">Spacecraft</button></a>' >> majortom/917.html
          echo '  <a href="https://brunurb.github.io/controls"><button type="button" class="nes-btn is-warning">Controls</button></a>' >> majortom/917.html
          echo '  <a href="https://brunurb.github.io/planets"><button type="button" class="nes-btn is-error">917</button></a>' >> majortom/917.html
          echo '  <a href="https://brunurb.github.io/917"><button type="button" class="nes-btn is-warning">917</button></a>' >> majortom/917.html
          echo '  </div>' >> majortom/917.html
          echo '</div>' >> majortom/917.html

          # Main content with centered text in mosaic div
          echo '<main>' >> majortom/917.html
          echo '<h1>Porsche 917</h1>' >> majortom/917.html
          echo '<div id="myMosaic" data-max-row-height="400" data-refit-on-resize="1" data-default-aspect-ratio="1">' >> majortom/917.html  # Set up mosaic options

          # Correctly add the images inside the myMosaic div, including data attributes for aspect ratio if needed
          for img in $(ls majortom/917/pictures | grep -E '\.jpeg$|\.jpg$|\.gif$|\.svg$|\.png$|\.webp$'); do
            # You can define an aspect ratio here if known
            aspect_ratio=1.5  # Placeholder aspect ratio; adjust as needed
            echo "<img src='917/pictures/$img' data-aspect-ratio='$aspect_ratio' alt='Gallery Image'/>" >> majortom/917.html
          done

          echo '</div>' >> majortom/917.html
          echo '</main>' >> majortom/917.html

          # Footer with copyright symbol
          echo '<footer>&copy; <a href="https://brunurb.github.io/">by brunurb</a></footer>' >> majortom/917.html

          # Include required scripts
          echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>' >> majortom/917.html
          echo '<script type="text/javascript" src="majortom/jquery.mosaic.js"></script>' >> majortom/917.html  # Include mosaic plugin
          echo '<script>$(document).ready(function() { $("#myMosaic").Mosaic(); });</script>' >> majortom/917.html  # Initialize the mosaic
          echo '</body></html>' >> majortom/917.html

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Action"
          git add majortom/917.html
          git commit -m "Regenerate 917.html for mosaic gallery" || echo "No changes to commit"
          git push origin master  # Make sure this matches your main branch
