jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Generate 917.html
        run: |
          # Creating the HTML structure for 917.html
          echo '<!DOCTYPE html><html lang="en">' > majortom/917.html
          echo '<head>' >> majortom/917.html
          echo '<meta charset="UTF-8">' >> majortom/917.html
          echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">' >> majortom/917.html
          echo '<title>Porsche 917</title>' >> majortom/917.html
          echo '<link rel="stylesheet" href="https://brunurb.github.io/main.css">' >> majortom/917.html
          echo '<link rel="stylesheet" href="https://brunurb.github.io/majortom/917/styles.css">' >> majortom/917.html
          echo '<link rel="stylesheet" href="https://brunurb.github.io/majortom/917/jquery.mosaic.css">' >> majortom/917.html
          echo '</head><body>' >> majortom/917.html
          echo '<div class="header">' >> majortom/917.html
          echo '  <a href="https://brunurb.github.io/"><span class="nes-icon home is-small"></span> brunurb</a>' >> majortom/917.html
          echo '  <div class="buttons">' >> majortom/917.html
          echo '    <a href="https://brunurb.github.io/majortom/astronaut"><button type="button" class="nes-btn is-primary">Astronaut</button></a>' >> majortom/917.html
          echo '    <a href="https://brunurb.github.io/majortom/spaceships"><button type="button" class="nes-btn is-success">Spacecraft</button></a>' >> majortom/917.html
          echo '    <a href="https://brunurb.github.io/majortom/controls"><button type="button" class="nes-btn is-warning">Controls</button></a>' >> majortom/917.html
          echo '    <a href="https://brunurb.github.io/majortom/planets"><button type="button" class="nes-btn is-error">Planets</button></a>' >> majortom/917.html
          echo '    <a href="https://brunurb.github.io/majortom/917"><button type="button" class="nes-btn is-warning">917</button></a>' >> majortom/917.html
          echo '  </div>' >> majortom/917.html
          echo '</div>' >> majortom/917.html

          # Main content with images
          echo '<main>' >> majortom/917.html
          echo '<h1>Porsche 917</h1>' >> majortom/917.html
          echo '<div id="myMosaic">' >> majortom/917.html

          for img in $(ls majortom/917/pictures | grep -E '\.jpeg$|\.jpg$|\.gif$|\.svg$|\.png$|\.webp$'); do
            echo "<img src='https://brunurb.github.io/majortom/917/pictures/$img' alt='Gallery Image' data-full='https://brunurb.github.io/majortom/917/pictures/$img' class='thumbnail' onclick='showImage(this.dataset.full)' />" >> majortom/917.html
          done

          echo '</div>' >> majortom/917.html
          echo '<div id="overlay" onclick="closeOverlay(event)"><div class="overlay-content"><span id="close">×</span><img id="overlay-image" src="" alt="Full Size Image" /></div></div>' >> majortom/917.html
          echo '</main>' >> majortom/917.html

          echo '<footer>© <a style="text-decoration:none" href="https://brunurb.github.io/">by brunurb</a></footer>' >> majortom/917.html

          # Include scripts
          echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>' >> majortom/917.html
          echo '<script src="https://brunurb.github.io/majortom/917/jquery.mosaic.js"></script>' >> majortom/917.html
          echo '<script type="text/javascript">' >> majortom/917.html
          echo 'document.addEventListener("DOMContentLoaded", function() {' >> majortom/917.html
          echo '    function showImage(src) {' >> majortom/917.html
          echo '        const overlay = document.getElementById("overlay");' >> majortom/917.html
          echo '        const overlayImage = document.getElementById("overlay-image");' >> majortom/917.html
          echo '        overlayImage.src = src;' >> majortom/917.html
          echo '        overlay.classList.add("show");' >> majortom/917.html
          echo '    }' >> majortom/917.html
          echo '    function closeOverlay(event) {' >> majortom/917.html
          echo '        if (event.target.id === "overlay" || event.target.id === "close") {' >> majortom/917.html
          echo '            const overlay = document.getElementById("overlay");' >> majortom/917.html
          echo '            overlay.classList.remove("show");' >> majortom/917.html
          echo '        }' >> majortom/917.html
          echo '    }' >> majortom/917.html
          echo '    const images = document.querySelectorAll("#myMosaic img");' >> majortom/917.html
          echo '    images.forEach(image => {' >> majortom/917.html
          echo '        image.addEventListener("click", function() {' >> majortom/917.html
          echo '            showImage(this.dataset.full);' >> majortom/917.html
          echo '        });' >> majortom/917.html
          echo '    });' >> majortom/917.html
          echo '    const overlay = document.getElementById("overlay");' >> majortom/917.html
          echo '    overlay.addEventListener("click", closeOverlay);' >> majortom/917.html
          echo '    const closeButton = document.getElementById("close");' >> majortom/917.html
          echo '    closeButton.addEventListener("click", closeOverlay);' >> majortom/917.html
          echo '});' >> majortom/917.html
          echo '</script>' >> majortom/917.html
          echo '</body></html>' >> majortom/917.html
