name: Astronaut

on:
  push:
    paths:
      - 'majortom/astronaut/pictures/**'
      - 'majortom/astronaut.html'
  workflow_dispatch:

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate astronaut.html
        run: |
          echo "Generating astronaut.html..."
          echo '<!DOCTYPE html><html lang="en">' > majortom/astronaut.html
          echo '<head>' >> majortom/astronaut.html
          echo '<meta charset="UTF-8">' >> majortom/astronaut.html
          echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">' >> majortom/astronaut.html
          echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">' >> majortom/astronaut.html
          echo '<title>Astronaut Gallery</title>' >> majortom/astronaut.html
          echo '<link rel="stylesheet" href="https://unpkg.com/nes.css/css/nes.css" />' >> majortom/astronaut.html
          echo '<style>' >> majortom/astronaut.html
          # Add your CSS here; you could include specific styles for astronaut.html
          echo '</style>' >> majortom/astronaut.html
          echo '</head><body>' >> majortom/astronaut.html

          # Header
          echo '<div class="header">' >> majortom/astronaut.html
          echo '  <a href="https://brunurb.github.io/"><span class="nes-icon home is-small"></span> brunurb</a>' >> majortom/astronaut.html
          echo '  <a href="https://brunurb.github.io/majortom/917.html" class="nes-btn">917</a>' >> majortom/astronaut.html
          echo '  <a href="https://brunurb.github.io/majortom/controls.html" class="nes-btn">Controls</a>' >> majortom/astronaut.html
          echo '  <a href="https://brunurb.github.io/majortom/planets.html" class="nes-btn">Planets</a>' >> majortom/astronaut.html
          echo '  <a href="https://brunurb.github.io/majortom/spaceships.html" class="nes-btn">Spaceships</a>' >> majortom/astronaut.html
          echo '</div>' >> majortom/astronaut.html

          # Main content with centered text in mosaic div
          echo '<main>' >> majortom/astronaut.html
          echo '<h1>Astronauts Gallery</h1>' >> majortom/astronaut.html
          echo '<div id="myMosaic">' >> majortom/astronaut.html

          # Loop to add images inside the myMosaic div
          for img in $(ls majortom/astronaut/pictures | grep -E '\.jpeg$|\.jpg$|\.gif$|\.svg$|\.png$|\.webp$'); do
            echo "<img src='https://brunurb.github.io/majortom/astronaut/pictures/$img' alt='Gallery Image' data-full='https://brunurb.github.io/majortom/astronaut/pictures/$img' class='thumbnail' onclick='showImage(this.dataset.full)' />" >> majortom/astronaut.html
          done

          echo '</div>' >> majortom/astronaut.html
          echo '<div id="overlay" onclick="closeOverlay(event)">' >> majortom/astronaut.html
          echo '  <div class="overlay-content">' >> majortom/astronaut.html
          echo '    <span id="close">&times;</span>' >> majortom/astronaut.html
          echo '    <img id="overlay-image" src="" alt="Full Size Image" />' >> majortom/astronaut.html
          echo '  </div>' >> majortom/astronaut.html
          echo '</div>' >> majortom/astronaut.html
          echo '</main>' >> majortom/astronaut.html

          # Footer
          echo '<footer>© <a href="https://brunurb.github.io/">by brunurb</a></footer>' >> majortom/astronaut.html

          # Include jQuery and custom scripts
          echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>' >> majortom/astronaut.html
          echo '<script type="text/javascript">' >> majortom/astronaut.html
          # Add the Overlay JS functionality here
          echo '</script>' >> majortom/astronaut.html
          echo '</body></html>' >> majortom/astronaut.html

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Action"
          git add majortom/astronaut.html
          git commit -m "Regenerate majortom/astronaut.html for gallery" || echo "No changes to commit"
          git push origin master  # Adjust this if your main branch is something else
