name: Update Majortom Gallery

on:
  push:
    paths:
      - 'majortom/pictures/**'   # Update to watch for image changes in majortom/pictures
      - 'majortom/index.html'     # Watch for changes to majortom/index.html
  workflow_dispatch:

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate index.html
        run: |
          echo "Generating index.html..."
          # Ensure the directory exists
          mkdir -p majortom
          # Start creating the index.html in the correct directory
          echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">' > majortom/index.html
          echo '<title>Majortom Gallery</title>' >> majortom/index.html
          echo '<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">' >> majortom/index.html
          echo '<link href="https://nostalgic-css.github.io/NES.css/css/nes.min.css" rel="stylesheet" />' >> majortom/index.html
          echo '<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>' >> majortom/index.html
          echo '<style>body { font-family: "Press Start 2P", serif; background-color: #f1faee; color: #457b9d; } #gallery { margin-top: 50px; display: flex; flex-wrap: wrap; gap: 16px; } .grid-item { width: calc(25% - 16px); } img { width: 100%; display: block; border-radius: 5px; }</style>' >> majortom/index.html
          echo '</head><body>' >> majortom/index.html

          # Menu code
          echo '<div id="menu" style="background-color: #457b9d; padding: 10px; position: fixed; width: 100%; top: 0; z-index: 1000;">' >> majortom/index.html
          echo '  <button type="button" class="nes-btn is-primary">Primary</button>' >> majortom/index.html
          echo '  <button type="button" class="nes-btn is-success">Success</button>' >> majortom/index.html
          echo '  <button type="button" class="nes-btn is-warning">Warning</button>' >> majortom/index.html
          echo '  <button type="button" class="nes-btn is-error">Error</button>' >> majortom/index.html
          echo '  <button type="button" class="nes-btn is-disabled" disabled>Disabled</button>' >> majortom/index.html
          echo '</div>' >> majortom/index.html

          # Gallery generation
          echo '<div id="gallery">' >> majortom/index.html
          for img in $(ls majortom/pictures | grep -E '\.jpeg$|\.jpg$|\.gif$|\.svg$|\.png$|\.webp$'); do
            echo "<div class='grid-item'><img src='pictures/$img' alt='Gallery Image' /></div>" >> majortom/index.html
          done
          echo '</div>' >> majortom/index.html

          # Masonry Initialization
          echo '<script>document.addEventListener("DOMContentLoaded", function() { const gallery = document.getElementById("gallery"); new Masonry(gallery, { itemSelector: ".grid-item", columnWidth: ".grid-item", percentPosition: true }); });</script>' >> majortom/index.html

          echo '</body></html>' >> majortom/index.html

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Action"
          git add majortom/index.html
          git commit -m "Regenerate index.html for Majortom gallery" || echo "No changes to commit"
          git push origin master  # Adjust this if your default branch is not master
