name: Update major tom

on:
  push:
    branches:
      - main  # Change this if you're using a different branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create image JSON
        run: |
          echo "[" > pictures.json
          for file in majortom/pictures/*.{jpg,jpeg,gif,png,webp,svg}; do
            if [[ -f $file ]]; then
              echo "  \"$(basename "$file")\"," >> pictures.json
            fi
          done
          # Remove trailing comma and close the JSON array
          sed -i '$ s/,$//' pictures.json
          echo "]" >> pictures.json

      - name: Commit and push changes
        run: |
          git config --local user.email "brunurb+github@gmail.com"
          git config --local user.name "brunurb"
          git add pictures.json
          git commit -m "Update images.json with new images" || echo "No changes to commit"
          git push
