name: planets

on:
  push:
    paths:
      - 'majortom/planets/pictures/**'
      - 'majortom/planets.html'
  workflow_dispatch:

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate planets.html
        run: |
          echo "Generating planets.html..."
          echo '<!DOCTYPE html><html lang="en">' > majortom/planets.html
          echo '<head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0">' >> majortom/planets.html
          echo '<title>Intergalactic Planets</title>' >> majortom/planets.html
          echo '<link rel="preconnect" href="https://fonts.googleapis.com">' >> majortom/planets.html
          echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>' >> majortom/planets.html
          echo '<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">' >> majortom/planets.html
          echo '<link rel="stylesheet" href="https://unpkg.com/nes.css/css/nes.css" />' >> majortom/planets.html
          echo '<style>' >> majortom/planets.html
          echo 'body { background-color: #142936; color: #92cfbf; margin: 0; font-family: "Press Start 2P", cursive; }' >> majortom/planets.html
          echo '.header { position: fixed; top: 0; left: 0; right: 0; background-color: #224357; padding: 5px; display: flex; justify-content: space-between; align-items: center; box-shadow: 0px 4px 10px rgba(8, 17, 23, 0.9); z-index: 10; }' >> majortom/planets.html
          echo '.header a { color: #cd3162; text-decoration: none; font-family: "Press Start 2P", cursive; font-size: 1em; }' >> majortom/planets.html
          echo '.buttons { display: flex; gap: 2px; }' >> majortom/planets.html
          echo '.nes-btn { margin-right: 2px; }' >> majortom/planets.html
          echo '.nes-btn:last-child { margin-right: 0; }' >> majortom/planets.html
          echo '#myMosaic { margin: 0; padding: 0; display: flex; flex-wrap: wrap; justify-content: center; margin-top: 20px; } img { margin: 0; display: block; border: none; max-width: calc(50% - 0px); height: auto; }' >> majortom/planets.html
          echo 'h1 { text-align: center; color: #dedcff; margin: 80px 0 14px; font-size: 14px; }' >> majortom/planets.html
          echo 'footer { text-align: left; padding: 10px; font-size: 10px; background-color: #224357; color: #92cfbf; }' >> majortom/planets.html
          echo 'footer a { color: inherit; text-decoration: none; }' >> majortom/planets.html
          echo '</style></head><body>' >> majortom/planets.html

          # Header
          echo '<div class="header">' >> majortom/planets.html
          echo '  <a href="https://brunurb.github.io/"><span class="nes-icon home is-small"></span> brunurb</a>' >> majortom/planets.html
          echo '  <div class="buttons">' >> majortom/planets.html
          echo '  <a href="https://brunurb.github.io/astronaut"><button type="button" class="nes-btn is-primary">Astronaut</button></a>' >> majortom/planets.html
          echo '  <a href="https://brunurb.github.io/spacecraft"><button type="button" class="nes-btn is-success">Spacecraft</button></a>' >> majortom/planets.html
          echo '  <a href="https://brunurb.github.io/controls"><button type="button" class="nes-btn is-warning">Controls</button></a>' >> majortom/planets.html
          echo '  <a href="https://brunurb.github.io/planets"><button type="button" class="nes-btn is-error">917</button></a>' >> majortom/planets.html
          echo '  <a href="https://brunurb.github.io/917"><button type="button" class="nes-btn is-warning">917</button></a>' >> majortom/planets.html
          echo '  </div>' >> majortom/planets.html
          echo '</div>' >> majortom/planets.html

          # Main content with centered text in mosaic div
          echo '<main>' >> majortom/planets.html
          echo '<h1>Intergalactic planets</h1>' >> majortom/planets.html
          echo '<div id="myMosaic">' >> majortom/planets.html

          # Correctly add the images inside the myMosaic div
          for img in $(ls planets/pictures | grep -E '\.jpeg$|\.jpg$|\.gif$|\.svg$|\.png$|\.webp$'); do
            echo "<img src='pictures/$img' alt='Gallery Image' />" >> majortom/planets.html
          done

          echo '</div>' >> majortom/planets.html
          echo '</main>' >> majortom/planets.html

          # Footer with copyright symbol
          echo '<footer>&copy; <a href="https://brunurb.github.io/">by brunurb</a></footer>' >> majortom/planets.html

          echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>' >> majortom/planets.html
          echo '<script type="text/javascript" src="jquery.mosaic.js"></script>' >> majortom/planets.html
          echo '<script type="text/javascript" src="scripts.js"></script>' >> majortom/planets.html
          echo '<script>$(document).ready(function() { $("#myMosaic").Mosaic({ maxRowHeight: 200 }); });</script>' >> majortom/planets.html
          echo '</body></html>' >> majortom/planets.html

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Action"
          git add majortom/planets.html
          git commit -m "Regenerate planets.html for mosaic gallery" || echo "No changes to commit"
          git push origin master  # Make sure this matches your main branch
