name: Spaceships

on:
  push:
    paths:
      - 'spaceships/pictures/**'
      - 'spaceships/index.html'
  workflow_dispatch:

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate index.html
        run: |
          echo "Generating index.html..."
          echo '<!DOCTYPE html><html lang="en">' > spaceships/index.html
          echo '<head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0">' >> spaceships/index.html
          echo '<title>Intergalactic Spaceships</title>' >> spaceships/index.html
          echo '<link rel="preconnect" href="https://fonts.googleapis.com">' >> spaceships/index.html
          echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>' >> spaceships/index.html
          echo '<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">' >> spaceships/index.html
          echo '<link rel="stylesheet" href="https://unpkg.com/nes.css/css/nes.css" />' >> spaceships/index.html
          echo '<style>' >> spaceships/index.html
          echo 'body { background-color: #65789C; color: #FFFFFF; margin: 0; font-family: "Press Start 2P", cursive; }' >> spaceships/index.html
          echo '.header { position: fixed; top: 0; left: 0; right: 0; background-color: #51607d; padding: 10px; display: flex; justify-content: flex-end; box-shadow: 0px 4px 10px rgba(57, 67, 86, 0.9); z-index: 10; }' >> spaceships/index.html
          echo '.header a { color: white; text-decoration: none; font-family: "Press Start 2P", cursive; font-size: 1em; }' >> spaceships/index.html  # Styling for the link
          echo '.nes-btn { margin-right: 2px; }' >> spaceships/index.html
          echo '.nes-btn:last-child { margin-right: 0; }' >> spaceships/index.html
          echo '#myMosaic { margin: 0; padding: 0; display: flex; flex-wrap: wrap; justify-content: center; margin-top: 60px; } img { margin: 0; display: block; border: none; max-width: calc(33.333% - 0px); height: auto; }' >> spaceships/index.html
          echo 'h1 { text-align: center; color: #213350; margin-top: 90px; }' >> spaceships/index.html
          echo '</style></head><body>' >> spaceships/index.html

          # Header
          echo '<div class="header">' >> spaceships/index.html
          echo '  <a href="https://brunurb.github.io/">brunurb</a>' >> spaceships/index.html  # Plain text link
          echo '  <div>' >> spaceships/index.html  # Div for button alignment
          echo '  <button type="button" class="nes-btn is-primary">Primary</button>' >> spaceships/index.html
          echo '  <button type="button" class="nes-btn is-success">Success</button>' >> spaceships/index.html
          echo '  <button type="button" class="nes-btn is-warning">Warning</button>' >> spaceships/index.html
          echo '  <button type="button" class="nes-btn is-error">Error</button>' >> spaceships/index.html
          echo '  <button type="button" class="nes-btn is-disabled">Disabled</button>' >> spaceships/index.html
          echo '  </div>' >> spaceships/index.html
          echo '</div>' >> spaceships/index.html

          # Main content with centered text in mosaic div
          echo '<main>' >> spaceships/index.html
          echo '<h1>Intergalactic Spaceships</h1>' >> spaceships/index.html
          echo '<div id="myMosaic">' >> spaceships/index.html

          # Correctly add the images inside the myMosaic div
          for img in $(ls spaceships/pictures | grep -E '\.jpeg$|\.jpg$|\.gif$|\.svg$|\.png$|\.webp$'); do
            echo "<img src='pictures/$img' alt='Gallery Image' />" >> spaceships/index.html
          done

          echo '</div>' >> spaceships/index.html
          echo '</main>' >> spaceships/index.html

          echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>' >> spaceships/index.html
          echo '<script type="text/javascript" src="jquery.mosaic.js"></script>' >> spaceships/index.html
          echo '<script type="text/javascript" src="scripts.js"></script>' >> spaceships/index.html
          echo '<script>$(document).ready(function() { $("#myMosaic").Mosaic(); });</script>' >> spaceships/index.html
          echo '</body></html>' >> spaceships/index.html

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Action"
          git add spaceships/index.html
          git commit -m "Regenerate index.html for mosaic gallery" || echo "No changes to commit"
          git push origin master  # Make sure this matches your main branch
