name: Vectors

on:
  push:
    paths:
      - 'brunurb.github.io/majortom/vectors.html'
      - 'brunurb.github.io/Mansonery/files/images/**'  # Monitor changes in the images directory
  workflow_dispatch:

jobs:
  update-vectors-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main GitHub Pages repository
        uses: actions/checkout@v2
        with:
          repository: brunurb/brunurb.github.io
          path: brunurb.github.io  # Check out into the 'brunurb.github.io' directory

      - name: Checkout Mansonery repository for images
        uses: actions/checkout@v2
        with:
          repository: brunurb/Mansonery
          path: Mansonery  # Check out into the 'Mansonery' directory

      - name: Generate vectors.html
        run: |
          echo "Generating vectors.html..."
          # Starting the HTML document
          echo '<!DOCTYPE html><html lang="en">' > brunurb.github.io/majortom/vectors.html
          echo '<head>' >> brunurb.github.io/majortom/vectors.html
          echo '  <meta charset="UTF-8">' >> brunurb.github.io/majortom/vectors.html
          echo '  <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> brunurb.github.io/majortom/vectors.html
          echo '  <title>Vectors Gallery</title>' >> brunurb.github.io/majortom/vectors.html
          echo '  <link rel="stylesheet" href="https://brunurb.github.io/majortom/main.css">' >> brunurb.github.io/majortom/vectors.html
          # Additional CSS, styles, and JavaScript setup...

          echo '<h1>Vectors Gallery</h1>' >> brunurb.github.io/majortom/vectors.html
          echo '    <div id="myMosaic">' >> brunurb.github.io/majortom/vectors.html
          
          # Find images in the Mansonery/files/images directory
          echo "Searching for images in 'Mansonery/files/images':"
          find "Mansonery/files/images" -type f \( -iname "*.jpeg" -o -iname "*.jpg" -o -iname "*.gif" -o -iname "*.svg" -o -iname "*.png" -o -iname "*.webp" \) | while IFS= read -r img; do
            img_name=$(basename "$img")       # Extracting the filename
            img_url="https://brunurb.github.io/Mansonery/files/images/$img_name"  # Use the GitHub Pages URL
            echo "<img src='$img_url' alt='Gallery Image' data-full='$img_url' class='thumbnail' onclick='showImage(this.dataset.full)' />" >> brunurb.github.io/majortom/vectors.html
            echo "Added image: $img_url"  # Log added image URLs
          done
          echo '    </div>' >> brunurb.github.io/majortom/vectors.html

          # Closing the HTML document with footer and scripts...
          echo '  <footer>' >> brunurb.github.io/majortom/vectors.html
          echo '    <p>© 2024 brunurb</p>' >> brunurb.github.io/majortom/vectors.html
          echo '  </footer>' >> brunurb.github.io/majortom/vectors.html
          echo '</body></html>' >> brunurb.github.io/majortom/vectors.html

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Action"
          git add brunurb.github.io/majortom/vectors.html
          git commit -m "Regenerate majortom/vectors.html with updated images from Mansonery" || echo "No changes to commit"
          git push origin master  # Ensure this matches your main branch
