name: Vectors

on:
  push:
    paths:
      - 'majortom/vectors.html'  # Trigger this workflow when this specific file changes
  workflow_dispatch:

jobs:
  update-gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v2

      - name: Checkout images from the main GitHub Pages repository
        uses: actions/checkout@v2
        with:
          repository: brunurb/brunurb.github.io  # This is the correct repository that contains your images
          path: Mansonery  # Directory to clone into
          ref: master  # Specify the branch

      - name: Generate vectors.html
        run: |
          echo "Generating vectors.html..."
          echo '<!DOCTYPE html><html lang="en">' > majortom/vectors.html
          echo '<head>' >> majortom/vectors.html
          echo '<meta charset="UTF-8">' >> majortom/vectors.html
          echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">' >> majortom/vectors.html
          echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">' >> majortom/vectors.html
          echo '<title>Intergalactic vectors</title>' >> majortom/vectors.html
          echo '<link rel="preconnect" href="https://fonts.googleapis.com">' >> majortom/vectors.html
          echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>' >> majortom/vectors.html
          echo '<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">' >> majortom/vectors.html
          echo '<link rel="stylesheet" href="https://unpkg.com/nes.css/css/nes.css" />' >> majortom/vectors.html
          echo '<link rel="stylesheet" type="text/css" href="https://brunurb.github.io/majortom/jquery.mosaic.css" />' >> majortom/vectors.html
          # Include your CSS styles here...
          echo '</head><body>' >> majortom/vectors.html

          # Adding header and main elements
          echo '<div class="header">' >> majortom/vectors.html
          echo '  <a href="https://brunurb.github.io/"><span class="nes-icon home is-small"></span> brunurb</a>' >> majortom/vectors.html
          echo '  <div class="buttons">' >> majortom/vectors.html
          echo '  <a href="https://brunurb.github.io/majortom/astronaut"><button type="button" class="nes-btn is-primary">Astronaut</button></a>' >> majortom/vectors.html
          echo '  <a href="https://brunurb.github.io/majortom/spaceships"><button type="button" class="nes-btn is-success">Spacecraft</button></a>' >> majortom/vectors.html
          echo '  <a href="https://brunurb.github.io/majortom/vectors"><button type="button" class="nes-btn is-warning">Vectors</button></a>' >> majortom/vectors.html
          echo '  <a href="https://brunurb.github.io/majortom/planets"><button type="button" class="nes-btn is-error">Planets</button></a>' >> majortom/vectors.html
          echo '  <a href="https://brunurb.github.io/majortom/917"><button type="button" class="nes-btn is-warning">917</button></a>' >> majortom/vectors.html
          echo '  </div>' >> majortom/vectors.html
          echo '</div>' >> majortom/vectors.html

          echo '<main>' >> majortom/vectors.html
          echo '<h1>Vectors</h1>' >> majortom/vectors.html
          echo '<div id="myMosaic">' >> majortom/vectors.html

          # Loop through images in the checked out Mansonery directory
          for img in $(ls Mansonery/files/images/*.{jpeg,jpg,gif,svg,png,webp} 2>/dev/null); do
            img_name=$(basename "$img")
            raw_url="https://raw.githubusercontent.com/brunurb/brunurb.github.io/master/Mansonery/files/images/$img_name"
            echo "<img src='$raw_url' alt='Gallery Image' data-full='$raw_url' class='thumbnail' onclick='showImage(this.dataset.full)' />" >> majortom/vectors.html
          done

          echo '</div>' >> majortom/vectors.html
          echo '<div id="overlay" onclick="closeOverlay(event)">' >> majortom/vectors.html
          echo '  <div class="overlay-content">' >> majortom/vectors.html
          echo '    <span id="close">×</span>' >> majortom/vectors.html
          echo '    <img id="overlay-image" src="" alt="Full Size Image" />' >> majortom/vectors.html
          echo '  </div>' >> majortom/vectors.html
          echo '</div>' >> majortom/vectors.html
          echo '</main>' >> majortom/vectors.html

          # Include footer and scripts
          echo '<footer>© <a style="text-decoration:none" href="https://brunurb.github.io/">by brunurb</a></footer>' >> majortom/vectors.html
          echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>' >> majortom/vectors.html
          echo '<script type="text/javascript" src="https://brunurb.github.io/majortom/jquery.mosaic.js"></script>' >> majortom/vectors.html

          # Add JavaScript for overlay functionality
          echo '<script type="text/javascript">' >> majortom/vectors.html
          echo 'document.addEventListener("DOMContentLoaded", function() {' >> majortom/vectors.html
          echo '    function showImage(src) {' >> majortom/vectors.html
          echo '        const overlay = document.getElementById("overlay");' >> majortom/vectors.html
          echo '        const overlayImage = document.getElementById("overlay-image");' >> majortom/vectors.html
          echo '        overlayImage.src = src;' >> majortom/vectors.html
          echo '        overlay.classList.add("show");' >> majortom/vectors.html
          echo '    }' >> majortom/vectors.html

          echo '    function closeOverlay(event) {' >> majortom/vectors.html
          echo '        if (event.target.id === "overlay" || event.target.id === "close") {' >> majortom/vectors.html
          echo '            const overlay = document.getElementById("overlay");' >> majortom/vectors.html
          echo '            overlay.classList.remove("show");' >> majortom/vectors.html
          echo '        }' >> majortom/vectors.html
          echo '    }' >> majortom/vectors.html

          echo '    const images = document.querySelectorAll("#myMosaic img");' >> majortom/vectors.html
          echo '    images.forEach(image => {' >> majortom/vectors.html
          echo '        image.addEventListener("click", function() {' >> majortom/vectors.html
          echo '            showImage(this.dataset.full);' >> majortom/vectors.html
          echo '        });' >> majortom/vectors.html
          echo '    });' >> majortom/vectors.html

          echo '    const overlay = document.getElementById("overlay");' >> majortom/vectors.html
          echo '    overlay.addEventListener("click", closeOverlay);' >> majortom/vectors.html
          echo '    const closeButton = document.getElementById("close");' >> majortom/vectors.html
          echo '    closeButton.addEventListener("click", closeOverlay);' >> majortom/vectors.html
          echo '    $("#myMosaic").Mosaic();' >> majortom/vectors.html
          echo '});' >> majortom/vectors.html
          echo '</script>' >> majortom/vectors.html
          echo '</body></html>' >> majortom/vectors.html

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Action"
          git add majortom/vectors.html
          git commit -m "Regenerate majortom/vectors.html with updated images" || echo "No changes to commit"
          git push origin master  # Ensure this matches your main branch
